# DATABASE CONFIGURATION
spring.datasource.url=
spring.datasource.username=user_name here
spring.datasource.password=password here

spring.datasource.driver-class-name=

# HIBERNATE
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=

# JAVAFX PROJECT (disable web server)
spring.main.web-application-type=
